# Don't print a new line at the start of the prompt
add_newline = true

# Pipes â•°â”€ â•­â”€
# Powerline symbols: î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff: ó°œ¥ î©± ï‹ ï€ ï’¶ ó°‰‹

format = """
$cmd_duration ó°œ¥ $directory 
$character
"""

# Command duration
[cmd_duration]
min_time = 0
format = ' [î‚¶](bold fg:yellow)[ó°ª¢ $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow)'

# Username
[username]
show_always = true
style_user = "bold bg:cyan fg:black"
style_root = "bold bg:red fg:white"
format = "[î‚¶](bold fg:cyan)[$user]($style)[î‚´](bold fg:cyan)"

# Hostname
[hostname]
ssh_only = false
format = "[â€¢$hostname](bg:cyan bold fg:black)[î‚´](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

# Directory
[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:green)[ó°‰‹ $path]($style)[î‚´](bold fg:green)'

[directory.substitutions]
"qemu" = " ï’© "
"docs" = " ï’¥ "
"down" = " ï‰ "
"music" = " ó°ˆ "
"pictures" = " ï "
"videos" = " ï”¬ "
"gitHub" = " ó°Š¤ "
"code" = " ï’‰ "
"content" = " âœ¨ "

# Git branch
[git_branch]
style = "bg:cyan fg:black"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = '[î‚¶](bold fg:cyan)[ó°œ¥ $branch(:$remote_branch)]($style)[î‚´](bold fg:cyan)'

# Git commit
[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

# Git state
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

# Git status
[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤·"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

# Character (prompt symbol)
[character]
success_symbol = "  [î©± ï‹](bold fg:blue)"
error_symbol = "  [ğŸ’€ ï‹](bold fg:red)"

# Package (disabled)
[package]
disabled = true

# Memory (disabled)
[memory_usage]
disabled = true

# Time (disabled)
[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

# Line break
[line_break]
disabled = false
